<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="0" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="84" started-at="2019-12-13T02:24:40Z" finished-at="2019-12-13T02:24:40Z">
    <groups>
      <group name="smoke">
        <method signature="DulicateCreateUserTst.createSuperUser_CopyOfCreateUserTst()[pri:0, instance:com.freecrm.testcases.DulicateCreateUserTst@17d0008]" name="createSuperUser_CopyOfCreateUserTst" class="com.freecrm.testcases.DulicateCreateUserTst"/>
      </group> <!-- smoke -->
    </groups>
    <test name="Default test" duration-ms="84" started-at="2019-12-13T02:24:40Z" finished-at="2019-12-13T02:24:40Z">
      <class name="com.freecrm.testcases.DulicateCreateUserTst">
        <test-method status="PASS" signature="befrClass()[pri:0, instance:com.freecrm.testcases.DulicateCreateUserTst@17d0008]" name="befrClass" is-config="true" duration-ms="23" started-at="2019-12-13T02:24:40Z" finished-at="2019-12-13T02:24:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- befrClass -->
        <test-method status="FAIL" signature="beforeClassInTest()[pri:0, instance:com.freecrm.testcases.DulicateCreateUserTst@17d0008]" name="beforeClassInTest" is-config="true" duration-ms="4" started-at="2019-12-13T02:24:40Z" finished-at="2019-12-13T02:24:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
valis not matching expected [55] but found [33],
abc vnvv vnc expected [55] but found [223],
 expected [ANAD] but found [rVI]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
valis not matching expected [55] but found [33],
abc vnvv vnc expected [55] but found [223],
 expected [ANAD] but found [rVI]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.freecrm.testcases.DulicateCreateUserTst.beforeClassInTest(DulicateCreateUserTst.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClassInTest -->
        <test-method status="SKIP" signature="runbeforeMethod(java.lang.reflect.Method)[pri:0, instance:com.freecrm.testcases.DulicateCreateUserTst@17d0008]" name="runbeforeMethod" is-config="true" duration-ms="0" started-at="2019-12-13T02:24:40Z" finished-at="2019-12-13T02:24:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runbeforeMethod -->
        <test-method status="SKIP" signature="createSuperUser_CopyOfCreateUserTst()[pri:0, instance:com.freecrm.testcases.DulicateCreateUserTst@17d0008]" name="createSuperUser_CopyOfCreateUserTst" duration-ms="0" started-at="2019-12-13T02:24:40Z" description="creating Super User" finished-at="2019-12-13T02:24:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
valis not matching expected [55] but found [33],
abc vnvv vnc expected [55] but found [223],
 expected [ANAD] but found [rVI]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
valis not matching expected [55] but found [33],
abc vnvv vnc expected [55] but found [223],
 expected [ANAD] but found [rVI]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.freecrm.testcases.DulicateCreateUserTst.beforeClassInTest(DulicateCreateUserTst.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSuperUser_CopyOfCreateUserTst -->
        <test-method status="SKIP" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.freecrm.testcases.DulicateCreateUserTst@17d0008]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-12-13T02:24:40Z" finished-at="2019-12-13T02:24:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="runbeforeMethod(java.lang.reflect.Method)[pri:0, instance:com.freecrm.testcases.DulicateCreateUserTst@17d0008]" name="runbeforeMethod" is-config="true" duration-ms="0" started-at="2019-12-13T02:24:40Z" finished-at="2019-12-13T02:24:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runbeforeMethod -->
        <test-method status="SKIP" signature="createAdminUser_CopyOfCreateUserTst()[pri:1, instance:com.freecrm.testcases.DulicateCreateUserTst@17d0008]" name="createAdminUser_CopyOfCreateUserTst" duration-ms="0" started-at="2019-12-13T02:24:40Z" description="createSupAdmin  erU  ser" finished-at="2019-12-13T02:24:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
valis not matching expected [55] but found [33],
abc vnvv vnc expected [55] but found [223],
 expected [ANAD] but found [rVI]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
valis not matching expected [55] but found [33],
abc vnvv vnc expected [55] but found [223],
 expected [ANAD] but found [rVI]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.freecrm.testcases.DulicateCreateUserTst.beforeClassInTest(DulicateCreateUserTst.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAdminUser_CopyOfCreateUserTst -->
        <test-method status="SKIP" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.freecrm.testcases.DulicateCreateUserTst@17d0008]" name="afterMethod" is-config="true" duration-ms="0" started-at="2019-12-13T02:24:40Z" finished-at="2019-12-13T02:24:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="pleaseSkipME()[pri:1, instance:com.freecrm.testcases.DulicateCreateUserTst@17d0008]" name="pleaseSkipME" duration-ms="0" started-at="2019-12-13T02:24:40Z" description="createSupAdmin  erU  ser" depends-on-methods="com.freecrm.testcases.DulicateCreateUserTst.createAdminUser_CopyOfCreateUserTst" finished-at="2019-12-13T02:24:40Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DulicateCreateUserTst.pleaseSkipME()[pri:1, instance:com.freecrm.testcases.DulicateCreateUserTst@17d0008] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DulicateCreateUserTst.pleaseSkipME()[pri:1, instance:com.freecrm.testcases.DulicateCreateUserTst@17d0008] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pleaseSkipME -->
        <test-method status="SKIP" signature="closeBrowser()[pri:0, instance:com.freecrm.testcases.DulicateCreateUserTst@17d0008]" name="closeBrowser" is-config="true" duration-ms="0" started-at="2019-12-13T02:24:40Z" finished-at="2019-12-13T02:24:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.freecrm.testcases.DulicateCreateUserTst -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
